config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  resources :items, only: [:new]
  resources :store, only: [:index]
  resources :cats,  only: [:show]
  
  get 'store/cat_items', :to => 'store#cat_items'
  get 'store/spot_items', :to => 'store#spot_items'

#   resources :sessions do
#     get :token, on: :collection #-> /sessions/token (sessions#token controller action)
#  end
  root to: 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat.rb
class Cat < ApplicationRecord
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cat
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def show
    @cat = Cat.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    redirect_to user_path(params[:id])
  end

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    redirect_to store_cat_items_path
  end

  def cat_items
    @user_items = current_user.items.pluck(:name)
    @store_items = HashWithIndifferentAccess.new(YAML.load(File.open("#{Rails.root}/config/store_items.yml", 'r')))[:cat_items]
    @store_items = @store_items.each do |item| 
      item_owned(item)
    end
  end

  def spot_items
    @user_items = current_user.items.pluck(:name)
    @store_items = HashWithIndifferentAccess.new(YAML.load(File.open("#{Rails.root}/config/store_items.yml", 'r')))[:spot_items]
    @store_items = @store_items.each do |item| 
      item_owned(item)
    end
  end

  private def item_owned(item)
    if @user_items.include? item[:name]
      item[:owned] = true
    else
      item[:owned] = false
    end
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @cat = User.find(params[:id]).cat
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def humanize_boolean(val)
    val ? 'yep' : 'nope'
  end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_controller.rb
class ItemsController < ApplicationController
  def new
    ActiveRecord::Base.transaction do
      item = Item.new(name: items_params[:name], user: current_user)
      if item.save
        @user = User.find(current_user.id)
        @user.update!(bux: @user.bux - items_params[:price].to_i)
      end
    end

    redirect_to '/store'

  end

  private def items_params
    params.permit(:name, :price)
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/turbo_devise_helper.rb
module TurboDeviseHelper
end

app/views/cats/show.html.erb
<h1>meow</h1>

<h3> <%= @cat.name %> </h3>

app/views/home/index.html.erb
<h1>bonk</h1>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-light bg-light p-2">
  <a class="navbar-brand" href="<%= user_path(current_user) if current_user %>">Catbeach.club</a>
  <% if current_user %>
    <li class='nav-item'>
      <p> bux: <%= current_user.bux  %></p>
    </li>
  <% end %>
  <%= button_to "logout", destroy_user_session_path, method: :delete, class: 'btn' if current_user %>
</nav>

app/views/layouts/_tabs.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link <%= 'active' if params[:controller] == 'users' %>" href="<%= user_path(current_user)%>">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= 'active' if params[:controller] == 'store' %>" href="<%= store_index_path %>">Store</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Your Spot</a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= 'active' if params[:controller] == 'cats' %>" href="<%= cat_path(current_user.cat.id)%>">Your Cat</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Settings</a>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catbeach</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= render 'layouts/nav' %>
    <% if current_user %>
      <%= render 'layouts/tabs' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/store/_items_table.html.erb
<div class='d-flex'>
  <table class='table table-striped table-hover table-sm'>
    <thead class='thead-light'>
      <th>name</th>
      <th>description</th>
      <th>price</th>
      <th>available</th>
      <th>effects</th>
      <th>purchase?</th>
    <thead>
    <tbody>
      <% items.each do |item| %>
        <tr>
          <td><%= item[:name] %></td>
          <td><%= item[:description] %></td>
          <td><%= item[:price] %></td>
          <td><%= humanize_boolean(item[:available_to_buy]) %></td>
          <td><%= item[:bonuses].join(', ') %> </td>
          <% if item[:owned] %>
            <td> <button class='btn disabled btn-primary'> owned </button> </td>
          <% elsif item[:price] > current_user.bux %>
            <td> <button class='btn disabled btn-danger'> too $$$ </button> </td>
          <% else %>
            <td> 
              <div class='btn btn-success' href="/users">
              <%= link_to 'purchase', new_item_path(item)%>
              </div> 
            </td>
          <% end %>
        </tr>
      <% end %>
      
    </tbody>
  </table>

app/views/store/cat_items.html.erb
<h1>Welcome to the beach store!</h1>
<div class='d-flex flex-column'>
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="<%= store_cat_items_path %>">Cat</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= store_spot_items_path %>">Spot</a>
    </li>
  </ul>
  <%= render partial: 'items_table', locals: {items: @store_items, bong: 'rip'} %>
</div>

app/views/store/index.html.erb
<h1>Welcome to the beach store!</h1>
<div class='d-flex'>
  <table class='table table-striped table-hover table-sm w-50'>
    <thead class='thead-light'>
      <th>name</th>
      <th>description</th>
      <th>price</th>
      <th>available</th>
      <th>effects</th>
      <th>purchase?</th>
    <thead>
    <tbody>
      <% @store_items.each do |item| %>
        <tr>
          <td><%= item[:name] %></td>
          <td><%= item[:description] %></td>
          <td><%= item[:price] %></td>
          <td><%= humanize_boolean(item[:available_to_buy]) %></td>
          <td><%= item[:bonuses].join(', ') %> </td>
          <% if item[:owned] %>
            <td> <button class='btn disabled btn-primary'> owned </button> </td>
          <% elsif item[:price] > current_user.bux %>
            <td> <button class='btn disabled btn-danger'> too $$$ </button> </td>
          <% else %>
            <td> 
              <div class='btn btn-success' href="/users">
              <%= link_to 'purchase', new_item_path(item)%>
              </div> 
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class='w-50 d-flex justify-content-center align-items-center'>
    <p>this is where the image go</p>
  </div>
</div>

app/views/store/spot_items.html.erb
<h1>Welcome to the beach store!</h1>
<div class='d-flex flex-column'>
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link" href="<%= store_cat_items_path %>">Cat</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="<%= store_spot_items_path %>">Spot</a>
    </li>
  </ul>
  <%= render partial: 'items_table', locals: {items: @store_items, bong: 'rip'} %>
</div>

app/views/users/show.html.erb
<h1>welcome <%= current_user.email %> </h1>
<p> you have <%= current_user.bux %> bux to spend </p>
<p> cat <%= @cat.name %> </p>